name: Docker Image CI

on:
  push:
    branches: ["master"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

  schedule:
    # Runs "At 06:00 on Monday" (see https://crontab.guru)
    - cron: '0 6 * * 1'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker images
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./scripts/ci.sh
      shell: bash
